-- +micrate Up
-- SQL in section 'Up' is executed when this migration is applied
-- Loading all countries to the table
INSERT INTO countries(name, created_at, updated_at) VALUES("Afghanistan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Albania", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Algeria", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Andorra", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Angola", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Antigua and Barbuda", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Argentina", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Armenia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Australia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Austria", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Azerbaijan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Bahamas", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Bahrain", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Bangladesh", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Barbados", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Belarus", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Belgium", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Belize", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Benin", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Bhutan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Bolivia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Bosnia and Herzegovina", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Botswana", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Brazil", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Brunei", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Bulgaria", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Burkina Faso", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Burundi", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Cabo Verde", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Cambodia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Cameroon", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Canada", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Central African Republic (CAR)", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Chad", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Chile", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("China", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Colombia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Comoros", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Democratic Republic of the Congo", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Republic of the Congo", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Costa Rica", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Cote d'Ivoire", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Croatia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Cuba", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Cyprus", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Czech Republic", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Denmark", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Djibouti", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Dominica", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Dominican Republic", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Ecuador", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Egypt", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("El Salvador", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Equatorial Guinea", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Eritrea", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Estonia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Ethiopia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Fiji", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Finland", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("France", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Gabon", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Gambia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Georgia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Germany", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Ghana", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Greece", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Grenada", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Guatemala", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Guinea", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Guinea-Bissau", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Guyana", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Haiti", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Honduras", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Hungary", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Iceland", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("India", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Indonesia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Iran", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Iraq", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Ireland", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Israel", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Italy", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Jamaica", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Japan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Jordan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Kazakhstan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Kenya", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Kiribati", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Kosovo", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Kuwait", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Kyrgyzstan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Laos", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Latvia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Lebanon", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Lesotho", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Liberia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Libya", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Liechtenstein", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Lithuania", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Luxembourg", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Macedonia (FYROM)", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Madagascar", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Malawi", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Malaysia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Maldives", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Mali", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Malta", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Marshall Islands", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Mauritania", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Mauritius", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Mexico", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Micronesia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Moldova", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Monaco", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Mongolia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Montenegro", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Morocco", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Mozambique", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Myanmar (Burma)", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Namibia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Nauru", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Nepal", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Netherlands", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("New Zealand", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Nicaragua", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Niger", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Nigeria", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("North Korea", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Norway", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Oman", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Pakistan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Palau", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Palestine", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Panama", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Papua New Guinea", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Paraguay", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Peru", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Philippines", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Poland", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Portugal", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Qatar", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Romania", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Russia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Rwanda", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Saint Kitts and Nevis", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Saint Lucia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Saint Vincent and the Grenadines", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Samoa", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("San Marino", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Sao Tome and Principe", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Saudi Arabia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Senegal", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Serbia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Seychelles", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Sierra Leone", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Singapore", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Slovakia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Slovenia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Solomon Islands", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Somalia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("South Africa", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("South Korea", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("South Sudan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Spain", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Sri Lanka", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Sudan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Suriname", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Swaziland", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Sweden", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Switzerland", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Syria", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Taiwan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Tajikistan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Tanzania", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Thailand", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Timor-Leste", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Togo", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Tonga", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Trinidad and Tobago", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Tunisia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Turkey", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Turkmenistan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Tuvalu", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Uganda", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Ukraine", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("United Arab Emirates (UAE)", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("United Kingdom (UK)", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("United States of America (USA)", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Uruguay", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Uzbekistan", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Vanuatu", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Vatican City (Holy See)", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Venezuela", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Vietnam", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Yemen", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Zambia", NOW(), NOW());
INSERT INTO countries(name, created_at, updated_at) VALUES("Zimbabwe", NOW(), NOW());

-- +micrate Down
-- SQL section 'Down' is executed when this migration is rolled back
DELETE FROM countries;
